export const COUNTRIES = [
  // Arab Countries
  { code: 'EG', nameEn: 'Egypt', nameAr: 'مصر', currency: 'EGP' },
  { code: 'SA', nameEn: 'Saudi Arabia', nameAr: 'السعودية', currency: 'SAR' },
  { code: 'AE', nameEn: 'United Arab Emirates', nameAr: 'الإمارات', currency: 'AED' },
  { code: 'KW', nameEn: 'Kuwait', nameAr: 'الكويت', currency: 'KWD' },
  { code: 'QA', nameEn: 'Qatar', nameAr: 'قطر', currency: 'QAR' },
  { code: 'BH', nameEn: 'Bahrain', nameAr: 'البحرين', currency: 'BHD' },
  { code: 'OM', nameEn: 'Oman', nameAr: 'عُمان', currency: 'OMR' },
  { code: 'JO', nameEn: 'Jordan', nameAr: 'الأردن', currency: 'JOD' },
  { code: 'LB', nameEn: 'Lebanon', nameAr: 'لبنان', currency: 'LBP' },
  { code: 'SY', nameEn: 'Syria', nameAr: 'سوريا', currency: 'SYP' },
  { code: 'IQ', nameEn: 'Iraq', nameAr: 'العراق', currency: 'IQD' },
  { code: 'PS', nameEn: 'Palestine', nameAr: 'فلسطين', currency: 'ILS' },
  { code: 'YE', nameEn: 'Yemen', nameAr: 'اليمن', currency: 'YER' },
  { code: 'SD', nameEn: 'Sudan', nameAr: 'السودان', currency: 'SDG' },
  { code: 'LY', nameEn: 'Libya', nameAr: 'ليبيا', currency: 'LYD' },
  { code: 'TN', nameEn: 'Tunisia', nameAr: 'تونس', currency: 'TND' },
  { code: 'DZ', nameEn: 'Algeria', nameAr: 'الجزائر', currency: 'DZD' },
  { code: 'MA', nameEn: 'Morocco', nameAr: 'المغرب', currency: 'MAD' },
  { code: 'MR', nameEn: 'Mauritania', nameAr: 'موريتانيا', currency: 'MRU' },
  { code: 'SO', nameEn: 'Somalia', nameAr: 'الصومال', currency: 'SOS' },
  { code: 'DJ', nameEn: 'Djibouti', nameAr: 'جيبوتي', currency: 'DJF' },
  { code: 'KM', nameEn: 'Comoros', nameAr: 'جزر القمر', currency: 'KMF' },
  
  // Other Global Countries
  { code: 'US', nameEn: 'United States', nameAr: 'الولايات المتحدة', currency: 'USD' },
  { code: 'GB', nameEn: 'United Kingdom', nameAr: 'المملكة المتحدة', currency: 'GBP' },
  { code: 'CA', nameEn: 'Canada', nameAr: 'كندا', currency: 'CAD' },
  { code: 'AU', nameEn: 'Australia', nameAr: 'أستراليا', currency: 'AUD' },
  { code: 'DE', nameEn: 'Germany', nameAr: 'ألمانيا', currency: 'EUR' },
  { code: 'FR', nameEn: 'France', nameAr: 'فرنسا', currency: 'EUR' },
  { code: 'IT', nameEn: 'Italy', nameAr: 'إيطاليا', currency: 'EUR' },
  { code: 'ES', nameEn: 'Spain', nameAr: 'إسبانيا', currency: 'EUR' },
  { code: 'TR', nameEn: 'Turkey', nameAr: 'تركيا', currency: 'TRY' },
  { code: 'IN', nameEn: 'India', nameAr: 'الهند', currency: 'INR' },
  { code: 'PK', nameEn: 'Pakistan', nameAr: 'باكستان', currency: 'PKR' },
  { code: 'ID', nameEn: 'Indonesia', nameAr: 'إندونيسيا', currency: 'IDR' },
  { code: 'MY', nameEn: 'Malaysia', nameAr: 'ماليزيا', currency: 'MYR' },
];
